-- WoWLegends_GM/UI/Tabs/NPC.lua
-- NPC tooling: spawn/manage creatures, tweak their fields (.npc set ...),
-- and look up creatures / spawn info. Acts on the currently selected creature
-- unless a GUID/entry is given.

local addonName, WLGM = ...

-- ─── Spawn / Manage ────────────────────────────────────────────────────────
local SpawnManage = {
    { id="npc_add", label="Spawn creature", format=".npc add %s", level=3, group="NPC",
      args={ {key="id",placeholder="creatureid",numeric=true,width=110} },
      tooltip="Spawn a creature by its template id (saved to DB)." },
    { id="npc_add_temp", label="Spawn temp creature", format=".npc add temp", level=3, group="NPC",
      tooltip="Spawn a temporary creature near you (not saved to the database)." },
    { id="npc_delete", label="Delete creature", format=".npc delete %s", level=3, group="NPC", danger=true,
      args={ {key="guid",placeholder="guid (opt)",numeric=true,optional=true,width=110} },
      tooltip="Delete the creature with the given GUID, or the selected creature if blank. Irreversible." },
    { id="npc_move", label="Move spawn here", format=".npc move %s", level=2, group="NPC",
      args={ {key="guid",placeholder="guid (opt)",numeric=true,optional=true,width=110} },
      tooltip="Move the selected (or GUID) creature's spawn point to your coordinates." },
    { id="npc_load", label="Load spawn", format=".npc load %s", level=3, group="NPC",
      args={ {key="spawn",placeholder="spawnId",numeric=true,width=110} },
      tooltip="Load a creature spawn from the database into the world by its GUID." },
    { id="npc_follow", label="Follow me", format=".npc follow start", level=2, group="NPC",
      tooltip="Selected creature follows you until death/combat/etc." },
    { id="npc_unfollow", label="Stop following", format=".npc follow stop", level=2, group="NPC",
      tooltip="Selected (non-pet) creature stops following you." },
    { id="npc_tame", label="Tame creature", format=".npc tame", level=2, group="NPC",
      tooltip="Turn the targeted creature into your player pet." },
    { id="npc_say", label="Make it say", format=".npc say %s", level=2, group="NPC",
      args={ {key="msg",placeholder="message",width=180} },
      tooltip="Make the selected creature SAY the given message." },
    { id="npc_yell", label="Make it yell", format=".npc yell %s", level=2, group="NPC",
      args={ {key="msg",placeholder="message",width=180} },
      tooltip="Make the selected creature YELL the given message." },
    { id="npc_whisper", label="Make it whisper", format=".npc whisper %s %s", level=2, group="NPC",
      args={ {key="who",placeholder="player",fallback="target",width=120},{key="text",placeholder="text",width=160} },
      tooltip="Make the selected NPC whisper text to a player. .npc whisper <player> <text>" },
    { id="npc_textemote", label="Text emote", format=".npc textemote %s", level=2, group="NPC",
      args={ {key="id",placeholder="emoteid",numeric=true,width=100} },
      tooltip="Make the selected creature perform a text-emote by emote id." },
    { id="npc_playemote", label="Play emote", format=".npc playemote %s", level=2, group="NPC",
      args={ {key="id",placeholder="emoteid",numeric=true,width=100} },
      tooltip="Make the selected creature play an animated emote by emote id." },
    { id="respawn", label="Respawn selected", format=".respawn", level=2, group="NPC",
      tooltip="Respawn the selected unit immediately, ignoring its respawn timer." },
    { id="respawn_all", label="Respawn nearby", format=".respawn all", level=2, group="NPC",
      tooltip="Respawn all nearby creatures and gameobjects immediately." },
    { id="cometome", label="Come to me", format=".cometome", level=3, group="NPC",
      tooltip="Make the selected creature walk to your current location (not saved to DB)." },
    { id="npc_spawngroup", label="Spawn group", format=".npc spawngroup %s", level=3, group="NPC",
      args={ {key="gid",placeholder="groupId",numeric=true,width=100} },
      tooltip="Spawn every creature in the given spawn group." },
    { id="npc_despawngroup", label="Despawn group", format=".npc despawngroup %s", level=3, group="NPC", danger=true,
      args={ {key="gid",placeholder="groupId",numeric=true,width=100} },
      tooltip="Despawn every creature in the given spawn group." },
    { id="npc_near", label="List nearby spawns", format=".npc near %s", level=2, group="NPC",
      args={ {key="dist",placeholder="distance",numeric=true,width=100} },
      tooltip="List all database creature spawns within the given distance." },
}

-- ─── Set (field editing) ───────────────────────────────────────────────────
local Set = {
    { id="set_level", label="Set level", format=".npc set level %s", level=3, group="NPC",
      args={ {key="lvl",placeholder="level",numeric=true,width=90} },
      tooltip="Set the selected creature's level (1 to max player level + 3)." },
    { id="set_entry", label="Set entry", format=".npc set entry %s", level=3, group="NPC",
      args={ {key="entry",placeholder="entry",numeric=true,width=100} },
      tooltip="Swap the selected creature to another creature_template entry (not saved to DB)." },
    { id="set_model", label="Set model", format=".npc set model %s", level=3, group="NPC",
      args={ {key="id",placeholder="displayid",numeric=true,width=110} },
      tooltip="Change the selected creature's display/model id." },
    { id="set_flag", label="Set NPC flags", format=".npc set flag %s", level=3, group="NPC",
      args={ {key="flag",placeholder="npcflag",numeric=true,width=100} },
      tooltip="Set the NPC flags on the selected creature's template (applies after restart / grid reload)." },
    { id="set_faction_perm", label="Set faction (perm)", format=".npc set faction permanent %s", level=3, group="NPC",
      args={ {key="fid",placeholder="factionid",numeric=true,width=100} },
      tooltip="Permanently set the selected creature's faction to the given faction id." },
    { id="set_faction_temp", label="Set faction (temp)", format=".npc set faction temp %s", level=3, group="NPC",
      args={ {key="fid",placeholder="factionid",numeric=true,width=100} },
      tooltip="Temporarily set the selected creature's faction to the given faction id." },
    { id="set_faction_orig", label="Revert faction", format=".npc set faction original", level=3, group="NPC",
      tooltip="Revert a temporary faction change back to the creature's original faction." },
    { id="set_movetype", label="Set move type", format=".npc set movetype %s %s", level=3, group="NPC",
      args={ {key="guid",placeholder="guid (opt)",numeric=true,optional=true,width=100},{key="type",placeholder="stay/random/way",width=120} },
      tooltip="Set movement type (stay/random/way) and reset to respawn position. Existing waypoints are removed unless you add NODEL.\n.npc set movetype [guid] stay/random/way [NODEL]" },
    { id="set_phase", label="Set phase", format=".npc set phase %s", level=3, group="NPC",
      args={ {key="mask",placeholder="phasemask",numeric=true,width=100} },
      tooltip="Set the selected creature's (or pet's) phasemask. Creature state is saved to DB." },
    { id="set_wanderdist", label="Set wander dist", format=".npc set wanderdistance %s", level=3, group="NPC",
      args={ {key="dist",placeholder="distance",numeric=true,width=100} },
      tooltip="Adjust how far the selected creature wanders from its spawn." },
    { id="set_spawntime", label="Set spawn time", format=".npc set spawntime %s", level=3, group="NPC",
      args={ {key="time",placeholder="e.g. 10m30s",width=110} },
      tooltip="Set the selected creature's respawn time. Use a timestring like 10m30s." },
    { id="set_data", label="Set data", format=".npc set data %s %s", level=3, group="NPC",
      args={ {key="field",placeholder="field",numeric=true,width=80},{key="data",placeholder="data",numeric=true,width=80} },
      tooltip="Set a data field on the selected creature (for script testing)." },
    { id="set_link", label="Link respawn", format=".npc set link %s", level=3, group="NPC",
      args={ {key="guid",placeholder="creatureGUID",numeric=true,width=120} },
      tooltip="Link the selected creature's respawn to another creature (by GUID) staying alive." },
}

-- ─── Lookup / Info ─────────────────────────────────────────────────────────
local LookupInfo = {
    { id="npc_info", label="NPC info", format=".npc info %s", level=2, group="NPC",
      args={ {key="guid",placeholder="guid (opt)",numeric=true,optional=true,width=110} },
      tooltip="Show details (GUID, faction, flags, entry, model, level, health...) for the selected creature or a given GUID." },
    { id="npc_guid", label="NPC guid", format=".npc guid", level=2, group="NPC",
      tooltip="Show GUID, faction, NPC flags, entry id and model id for the selected creature." },
    { id="guid", label="Selected GUID", format=".guid", level=2, group="NPC",
      tooltip="Show the GUID of the currently selected character/creature." },
    { id="lookup_creature", label="Lookup creature", format=".lookup creature %s", level=1, group="NPC",
      args={ {key="q",placeholder="name part",width=150} },
      tooltip="Find creatures whose name contains the search text and list their creature ids." },
    { id="lookup_event", label="Lookup event", format=".lookup event %s", level=1, group="NPC",
      args={ {key="q",placeholder="event name",width=150} },
      tooltip="Find a game event id by name." },
    { id="distance", label="Distance to target", format=".distance", level=3, group="NPC",
      tooltip="Show the distance from you to the selected creature." },
}

WLGM.RegisterTab({
    id = "npc", label = "NPC",
    builder = function(parent)
        WLGM.BuildSubTabs(parent, {
            { label = "Spawn/Manage", rows = SpawnManage, layoutOpts = { sectionTitle = "Spawn & manage creatures", rowsPerColumn = 12, columnWidth = 420 } },
            { label = "Set",          rows = Set,          layoutOpts = { sectionTitle = "Edit creature fields", rowsPerColumn = 12, columnWidth = 420 } },
            { label = "Lookup/Info",  rows = LookupInfo,   layoutOpts = { sectionTitle = "Lookup & info" } },
        }, "npc")
    end,
})
