-- WoWLegends_GM/UI/Tabs/Player.lua
-- Player command tab: act on the selected/targeted player (or yourself).
-- Modify stats, cast/aura, learn/unlearn, reset, character ops, achievements,
-- titles, honor, skills, group/instance/pet, and guild management.

local addonName, WLGM = ...

-- Shared player-name arg: blank field falls back to the current target.
local function nameArg(opt) return { key="name", placeholder="player", fallback="target", optional=opt, width=150 } end

-- ─── Modify (.modify <field> <value>) ──────────────────────────────────────
local Modify = {
    { id="mod_hp", label="Set HP", format=".modify hp %s", level=2, group="Player",
      args={ {key="hp",placeholder="newhp",numeric=true} },
      tooltip="Set the HP of the selected player (yourself if none selected)." },
    { id="mod_mana", label="Set mana", format=".modify mana %s", level=2, group="Player",
      args={ {key="mana",placeholder="newmana",numeric=true} },
      tooltip="Set the mana of the selected player (yourself if none selected)." },
    { id="mod_rage", label="Set rage", format=".modify rage %s", level=2, group="Player",
      args={ {key="rage",placeholder="newrage",numeric=true} },
      tooltip="Set the rage of the selected player (yourself if none selected)." },
    { id="mod_energy", label="Set energy", format=".modify energy %s", level=2, group="Player",
      args={ {key="energy",placeholder="energy",numeric=true} },
      tooltip="Set the energy of the selected player (yourself if none selected)." },
    { id="mod_runic", label="Set runic power", format=".modify runicpower %s", level=2, group="Player",
      args={ {key="rp",placeholder="runicpower",numeric=true} },
      tooltip="Set the runic power of the selected player (yourself if none selected)." },
    { id="mod_money", label="Set money", format=".modify money %s", level=2, group="Player",
      args={ {key="money",placeholder="copper (+/-)",numeric=true,width=110} },
      tooltip="Add or remove money (in copper) for the selected player. Negative removes." },
    { id="mod_arena", label="Arena points", format=".modify arenapoints %s", level=2, group="Player",
      args={ {key="value",placeholder="amount",numeric=true} },
      tooltip="Add arena points to the selected player." },
    { id="mod_honor", label="Honor points", format=".modify honor %s", level=2, group="Player",
      args={ {key="value",placeholder="amount",numeric=true} },
      tooltip="Add honor points to the selected player." },
    { id="mod_talentpts", label="Talent points", format=".modify talentpoints %s", level=2, group="Player",
      args={ {key="amount",placeholder="amount",numeric=true} },
      tooltip="Set free talent points for the selected character or its pet. Resets at next levelup/login." },
    { id="mod_phase", label="Phase", format=".modify phase %s", level=2, group="Player",
      args={ {key="mask",placeholder="phasemask",numeric=true} },
      tooltip="Change the selected character's phasemask (with world-vision update). Reverts on relog or GM-mode toggle." },
    { id="mod_gender", label="Gender", format=".modify gender %s", level=2, group="Player",
      args={ {key="g",placeholder="gender",choices={"male","female"},width=110} },
      tooltip="Change the gender of the selected player. Use male or female." },
    { id="mod_drunk", label="Drunk level", format=".modify drunk %s", level=2, group="Player",
      args={ {key="value",placeholder="0-100",numeric=true} },
      tooltip="Set drunk level 0-100. 0 removes the drunk state, 100 is fully drunk." },
    { id="mod_standstate", label="Stand state", format=".modify standstate %s", level=2, group="Player",
      args={ {key="emote",placeholder="emoteid",numeric=true} },
      tooltip="Change your standing emote to the given emote id." },
    { id="mod_scale", label="Scale", format=".modify scale %s", level=2, group="Player",
      args={ {key="scale",placeholder="0.1-10",numeric=true} },
      tooltip="Resize the selected player or creature. Rate 0.1 to 10 (1 = normal)." },
    { id="mod_faction", label="Faction (creature)", format=".modify faction %s %s %s %s", level=3, group="Player",
      args={ {key="faction",placeholder="factionid",numeric=true},{key="flag",placeholder="flagid",numeric=true},{key="npc",placeholder="npcflag",numeric=true},{key="dyn",placeholder="dynflag",numeric=true} },
      tooltip="Set faction and flags of the selected creature." },
    { id="mod_reputation", label="Reputation", format=".modify reputation %s %s", level=2, group="Player",
      args={ {key="repid",placeholder="repId",numeric=true},{key="value",placeholder="value/rank",width=120} },
      tooltip="Set the selected player's reputation with faction repId to a value or rank name. Use .lookup faction to find ids." },
    { id="mod_speed", label="Speed (type)", format=".modify speed %s %s", level=2, group="Player",
      args={ {key="type",placeholder="speed type",choices={"all","fly","walk","backwalk","swim"},width=130},{key="rate",placeholder="0.1-50",numeric=true} },
      tooltip="Set a movement speed of the selected player. Types: fly, all, walk, backwalk, swim. Rate 0.1-50." },
    { id="mod_mount", label="Mount", format=".modify mount %s %s", level=2, group="Player",
      args={ {key="id",placeholder="displayId",numeric=true},{key="speed",placeholder="0.1-50",numeric=true} },
      tooltip="Set CreatureDisplayID as mount and a speed value between 0.1 and 50." },
}

-- ─── Spells (cast / aura / cooldown / spellinfo) ───────────────────────────
local Spells = {
    { id="cast", label="Cast spell", format=".cast %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Cast a spell on your target (self if none selected)." },
    { id="cast_self", label="Cast on self", format=".cast self %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Make the selected target cast the spell on itself." },
    { id="cast_target", label="Cast at victim", format=".cast target %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Make the selected target cast the spell on its current victim." },
    { id="cast_back", label="Cast back at me", format=".cast back %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Make the selected target cast the spell on your character." },
    { id="aura", label="Add aura", format=".aura %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Apply the aura from the given spell to the selected unit." },
    { id="aura_stack", label="Aura stacks", format=".aura stack %s %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true},{key="stacks",placeholder="stacks",numeric=true} },
      tooltip="Modify the stack count of an already-applied aura on the selected unit." },
    { id="unaura", label="Remove aura", format=".unaura %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Remove the aura of the given spell from the selected unit." },
    { id="cooldown", label="Clear cooldown", format=".cooldown %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid (opt)",numeric=true,optional=true,width=110} },
      tooltip="Remove one spell cooldown, or all cooldowns if no spell id is given, from the selected character." },
    { id="combatstop", label="Stop combat", format=".combatstop %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Stop combat for the selected/named character (self if non-player selected)." },
    { id="spellinfo_all", label="Spell info (all)", format=".spellinfo all %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Display all data for a spell: attributes, properties, effects and targets." },
    { id="spellinfo_eff", label="Spell effects", format=".spellinfo effects %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Display effect data for a spell (type, aura, base points, trigger spell, etc.)." },
    { id="lk_spell", label="Lookup spell", format=".lookup spell %s", level=1, group="Player",
      args={ {key="q",placeholder="name part",width=130} },
      tooltip="Find spells by name and return their spell ids." },
}

-- ─── Learn / Unlearn ───────────────────────────────────────────────────────
local Learn = {
    { id="learn", label="Learn spell", format=".learn %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Teach the selected character a spell. Add 'all' in usage to learn all ranks." },
    { id="unlearn", label="Unlearn spell", format=".unlearn %s", level=2, group="Player",
      args={ {key="spell",placeholder="spellid",numeric=true} },
      tooltip="Remove a spell from the selected player." },
    { id="learn_default", label="Learn default", format=".learn all default %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Learn all default race/class spells and quest-rewarded spells for the selected/named player." },
    { id="learn_class", label="Learn my class", format=".learn all my class", level=2, group="Player",
      tooltip="Learn all spells (trainer, talent, quest reward) for your class." },
    { id="learn_talents", label="Learn my talents", format=".learn all my talents", level=2, group="Player",
      tooltip="Learn all talents available for your class." },
    { id="learn_trainer", label="Learn my trainer", format=".learn all my trainer", level=2, group="Player",
      tooltip="Learn all spells taught by trainers for your class." },
    { id="learn_quest", label="Learn my quest", format=".learn all my quest", level=2, group="Player",
      tooltip="Learn all spells rewarded from quests for your class." },
    { id="learn_crafts", label="Learn all crafts", format=".learn all crafts", level=2, group="Player",
      tooltip="Learn all professions and recipes." },
    { id="learn_recipes", label="Learn recipes", format=".learn all recipes %s", level=2, group="Player",
      args={ {key="prof",placeholder="profession (opt)",optional=true,width=140} },
      tooltip="Learn all recipes of a profession and max its skill (e.g. enchanting)." },
    { id="learn_lang", label="Learn languages", format=".learn all lang", level=2, group="Player",
      tooltip="Learn all languages." },
    { id="learn_gm", label="Learn GM spells", format=".learn all gm", level=2, group="Player",
      tooltip="Learn all default Game Master spells." },
    { id="learn_pettalents", label="Learn pet talents", format=".learn all my pettalents", level=2, group="Player",
      tooltip="Learn all talents for your pet's creature type (hunter pets only)." },
}

-- ─── Reset (.reset ...) ────────────────────────────────────────────────────
local Reset = {
    { id="reset_talents", label="Reset talents", format=".reset talents %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Remove all talents of the targeted player (and pets) or a named offline character." },
    { id="reset_spells", label="Reset spells", format=".reset spells %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Remove all non-original spells from the spellbook (online or offline character)." },
    { id="reset_stats", label="Reset stats", format=".reset stats %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Recalculate all stats of the targeted player to their defaults at the current level." },
    { id="reset_level", label="Reset level", format=".reset level %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Reset level to 1 including stats and talents. Equipped items with higher level requirements can be lost." },
    { id="reset_achievements", label="Reset achievements", format=".reset achievements %s", level=4, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Reset achievement data for the selected or named character. Event-based progress (kills/casts) is lost." },
    { id="reset_honor", label="Reset honor", format=".reset honor %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Reset all honor data for the targeted character." },
    { id="reset_items_all", label="Reset all items", format=".reset items all %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Delete ALL items of the player (equipped, bags, bank, keyring, currency, buyback). Irreversible." },
    { id="reset_items_bags", label="Reset bags", format=".reset items bags %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Delete all items in the selected player's bags." },
    { id="reset_items_bank", label="Reset bank", format=".reset items bank %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Delete all items in the selected player's bank." },
    { id="reset_items_equip", label="Reset equipped", format=".reset items equipped %s", level=3, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Delete all items equipped on the target player." },
}

-- ─── Character (.character ...) ─────────────────────────────────────────────
local Character = {
    { id="char_level", label="Set level", format=".character level %s %s", level=2, group="Player",
      args={ nameArg(true), {key="level",placeholder="level (opt)",numeric=true,optional=true} },
      tooltip="Set the level of the named (or selected) character. Omit level to add one." },
    { id="char_rename", label="Rename", format=".character rename %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Mark the selected/named character for rename at next login." },
    { id="char_customize", label="Customize", format=".character customize %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Mark the selected/named character for appearance customize at next login." },
    { id="char_changerace", label="Change race", format=".character changerace %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Mark the named character to change race at next login." },
    { id="char_changefaction", label="Change faction", format=".character changefaction %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Mark the named character to change faction at next login." },
    { id="char_titles", label="List titles", format=".character titles %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Show the known titles list for the selected or named player." },
    { id="char_reputation", label="List reputation", format=".character reputation %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Show reputation information for the selected or named player." },
    { id="char_prof", label="List professions", format=".character check profession %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Show the known professions for the selected player." },
    { id="char_changeacct", label="Change account", format=".character changeaccount %s %s", level=3, group="Player", danger=true,
      args={ {key="account",placeholder="new account",width=140},{key="name",placeholder="char name",width=140} },
      tooltip="Move the named character to another account. Kicks the player if online." },
    { id="char_erase", label="Erase character", format=".character erase %s", level=4, group="Player", danger=true,
      args={ {key="name",placeholder="char name",width=150} },
      tooltip="Permanently delete the named character. Irreversible." },
    { id="char_deleted_restore", label="Restore deleted", format=".character deleted restore %s", level=3, group="Player",
      args={ {key="ref",placeholder="guid|name",width=140} },
      tooltip="Restore a deleted character by GUID or name." },
    { id="char_deleted_delete", label="Delete deleted", format=".character deleted delete %s", level=4, group="Player", danger=true,
      args={ {key="ref",placeholder="guid|name",width=140} },
      tooltip="Completely and permanently delete the named/GUID deleted character." },
}

-- ─── Stats & progression (level / skills / achievements / titles / honor) ──
local Stats = {
    { id="levelup", label="Levelup", format=".levelup %s %s", level=2, group="Player",
      args={ nameArg(true), {key="num",placeholder="levels (opt)",numeric=true,optional=true} },
      tooltip="Increase/decrease the named (or selected) character's level by the given number (default +1)." },
    { id="maxskill", label="Max all skills", format=".maxskill", level=2, group="Player",
      tooltip="Set all skills of the targeted player to their maximum for the current level." },
    { id="setskill", label="Set skill", format=".setskill %s %s %s", level=2, group="Player",
      args={ {key="skill",placeholder="skillid",numeric=true},{key="level",placeholder="value",numeric=true},{key="max",placeholder="max (opt)",numeric=true,optional=true} },
      tooltip="Set a skill's current value and optional maximum on the selected character." },
    { id="ach_add", label="Add achievement", format=".achievement add %s", level=2, group="Player",
      args={ {key="ach",placeholder="id or link",width=130} },
      tooltip="Add an achievement (id or link) to the targeted player." },
    { id="title_add", label="Add title", format=".titles add %s", level=2, group="Player",
      args={ {key="title",placeholder="id or link",width=130} },
      tooltip="Add a title (id or shift-link) to the selected player's known titles." },
    { id="title_current", label="Set current title", format=".titles current %s", level=2, group="Player",
      args={ {key="title",placeholder="id or link",width=130} },
      tooltip="Set the current title for the selected player (added if not known)." },
    { id="title_remove", label="Remove title", format=".titles remove %s", level=2, group="Player", danger=true,
      args={ {key="title",placeholder="id or link",width=130} },
      tooltip="Remove a title from the selected player's known titles." },
    { id="honor_add", label="Add honor", format=".honor add %s", level=2, group="Player",
      args={ {key="amount",placeholder="amount",numeric=true} },
      tooltip="Add honor (gained today) to the selected player." },
    { id="honor_addkill", label="Add honor kill", format=".honor add kill", level=2, group="Player",
      tooltip="Count the targeted unit as one of your PvP kills today." },
    { id="lk_skill", label="Lookup skill", format=".lookup skill %s", level=1, group="Player",
      args={ {key="q",placeholder="name part",width=130} },
      tooltip="Find a skill by name and return its skill id." },
    { id="lk_title", label="Lookup title", format=".lookup title %s", level=1, group="Player",
      args={ {key="q",placeholder="name part",width=130} },
      tooltip="Find a title by name and return its id and index." },
    { id="lk_faction", label="Lookup faction", format=".lookup faction %s", level=1, group="Player",
      args={ {key="q",placeholder="name",width=130} },
      tooltip="Find the id of a faction by name." },
}

-- ─── Group / instance / pet / status ───────────────────────────────────────
local Groups = {
    { id="revive", label="Revive", format=".revive", level=2, group="Player",
      tooltip="Revive the selected player (yourself if none selected)." },
    { id="die", label="Kill", format=".die", level=2, group="Player", danger=true,
      tooltip="Kill the selected player (yourself if none selected)." },
    { id="damage", label="Damage", format=".damage %s", level=2, group="Player",
      args={ {key="amount",placeholder="amount",numeric=true} },
      tooltip="Apply damage to the target (flat melee damage with no school given)." },
    { id="grp_list", label="Group list", format=".group list %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="List all members of the player's group/party." },
    { id="grp_join", label="Group join", format=".group join %s %s", level=2, group="Player",
      args={ {key="member",placeholder="member of group",width=140}, nameArg(true) },
      tooltip="Add a player (or selected) to the group of the named group member." },
    { id="grp_remove", label="Group remove", format=".group remove %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Remove the given character from their group." },
    { id="grp_leader", label="Group leader", format=".group leader %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Set the given character as their group's leader." },
    { id="grp_disband", label="Group disband", format=".group disband %s", level=2, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Disband the given character's group." },
    { id="grp_revive", label="Group revive", format=".group revive %s", level=2, group="Player",
      args={ nameArg(true) },
      tooltip="Revive all group members of the given character (or self)." },
    { id="inst_listbinds", label="List instance binds", format=".instance listbinds", level=1, group="Player",
      tooltip="List the instance binds of the selected player." },
    { id="inst_unbind", label="Unbind instance", format=".instance unbind %s", level=2, group="Player", danger=true,
      args={ {key="map",placeholder="mapid|all",width=110} },
      tooltip="Clear all or some of the player's instance binds." },
    { id="pet_create", label="Create pet", format=".pet create", level=2, group="Player",
      tooltip="Create a pet from the selected creature." },
    { id="pet_list", label="List pets", format=".pet list %s", level=1, group="Player",
      args={ {key="ref",placeholder="player/GUID",width=130} },
      tooltip="List all pets owned by the specified player." },
    { id="pet_delete", label="Delete pet", format=".pet delete %s %s", level=3, group="Player", danger=true,
      args={ {key="ref",placeholder="player/GUID",width=130},{key="num",placeholder="petNumber",numeric=true} },
      tooltip="Delete the given pet number belonging to the specified player." },
}

-- ─── Guild (.guild ...) ────────────────────────────────────────────────────
local Guild = {
    { id="guild_create", label="Create guild", format=".guild create %s \"%s\"", level=2, group="Player",
      args={ nameArg(true), {key="guild",placeholder="guild name",width=160} },
      tooltip="Create a guild with the named (or selected) player as leader." },
    { id="guild_invite", label="Invite to guild", format=".guild invite %s \"%s\"", level=2, group="Player",
      args={ nameArg(true), {key="guild",placeholder="guild name",width=160} },
      tooltip="Add the named (or selected) player to a guild." },
    { id="guild_uninvite", label="Remove from guild", format=".guild uninvite %s", level=2, group="Player", danger=true,
      args={ nameArg(true) },
      tooltip="Remove the named (or selected) player from their guild." },
    { id="guild_rank", label="Set guild rank", format=".guild rank %s %s", level=2, group="Player",
      args={ nameArg(true), {key="rank",placeholder="rank # (0=GM)",numeric=true,width=110} },
      tooltip="Set the rank of the named (or selected) player. 0 = Guild Master, 1 = Officer, etc." },
    { id="guild_rename", label="Rename guild", format=".guild rename \"%s\" \"%s\"", level=2, group="Player",
      args={ {key="old",placeholder="guild name",width=150},{key="new",placeholder="new name",width=150} },
      tooltip="Rename a guild. Both names are quoted automatically." },
    { id="guild_info", label="Guild info", format=".guild info", level=2, group="Player",
      tooltip="Show information about the target's guild." },
    { id="guild_delete", label="Delete guild", format=".guild delete \"%s\"", level=2, group="Player", danger=true,
      args={ {key="guild",placeholder="guild name",width=160} },
      tooltip="Delete the named guild. Irreversible." },
}

WLGM.RegisterTab({
    id = "player", label = "Player",
    builder = function(parent)
        WLGM.BuildSubTabs(parent, {
            { label="Modify",    rows=Modify,    layoutOpts={ sectionTitle="Modify stats & attributes", rowsPerColumn=10, columnWidth=420 } },
            { label="Spells",    rows=Spells,    layoutOpts={ sectionTitle="Cast, auras & spell info", rowsPerColumn=12, columnWidth=420 } },
            { label="Learn",     rows=Learn,     layoutOpts={ sectionTitle="Learn & unlearn", rowsPerColumn=12, columnWidth=420 } },
            { label="Reset",     rows=Reset,     layoutOpts={ sectionTitle="Reset & wipe (destructive)", rowsPerColumn=10, columnWidth=420 } },
            { label="Character", rows=Character, layoutOpts={ sectionTitle="Character operations", rowsPerColumn=12, columnWidth=420 } },
            { label="Stats",     rows=Stats,     layoutOpts={ sectionTitle="Levels, skills, titles & honor", rowsPerColumn=12, columnWidth=420 } },
            { label="Groups",    rows=Groups,    layoutOpts={ sectionTitle="Group, instance, pet & status", rowsPerColumn=12, columnWidth=420 } },
            { label="Guild",     rows=Guild,     layoutOpts={ sectionTitle="Guild management" } },
        }, "player")
    end,
})
